/**
 * Writes .dsh-home/settings.yaml so DeepSeek Harness routes models through CheaperInference.
 *
 *   npm run setup:dsh                          # default model list
 *   npm run setup:dsh -- --models=deepseek-v4-flash,kimi-k3 --force
 */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const dshHome = join(root, ".dsh-home");
const settingsPath = join(dshHome, "settings.yaml");
const baseURL = "https://api.cheaperinference.com/v1";
// Agents call models through the AI Employee server's gateway, which adds the real key and meters cost per task.
const gatewayURL = `http://127.0.0.1:${Number(process.env.AI_EMPLOYEE_PORT || 7717)}/llm/v1`;
const force = process.argv.includes("--force");
const modelsArg = process.argv.find((a) => a.startsWith("--models="));
const models = modelsArg
  ? modelsArg.slice("--models=".length).split(",").map((m) => m.trim()).filter(Boolean)
  : ["deepseek-v4-flash"];

const key = process.env.CHEAPERINFERENCE_API_KEY;
if (!key) {
  console.warn("CHEAPERINFERENCE_API_KEY is not set in .env.local — skipping the model availability check.");
} else {
  try {
    const res = await fetch(`${baseURL}/models`, { headers: { Authorization: `Bearer ${key}` } });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const body = (await res.json()) as { data?: { id: string }[] };
    const available = (body.data ?? []).map((m) => m.id).sort();
    console.log(`CheaperInference serves ${available.length} models:\n  ${available.join("\n  ")}`);
    const missing = models.filter((m) => !available.includes(m));
    if (missing.length) console.warn(`\nNot in the catalog right now: ${missing.join(", ")}`);
  } catch (error) {
    console.warn(`Could not list CheaperInference models: ${(error as Error).message}`);
  }
}

const modelYaml = models
  .map((id) =>
    [`        - id: ${JSON.stringify(id)}`, ...(id.startsWith("deepseek") ? ["          compat:", "            thinkingFormat: deepseek"] : [])].join("\n"),
  )
  .join("\n");

const yaml = `# Generated by "npm run setup:dsh". Model routes for DeepSeek Harness.
# Requests go to the AI Employee server (${gatewayURL}), which forwards them to CheaperInference with the real
# API key. CHEAPERINFERENCE_API_KEY only has to be non-empty for the agents; it is never stored here.
llm-pi-ai:
  providers:
    cheaperinference:
      displayName: CheaperInference
      apiKeyEnv: CHEAPERINFERENCE_API_KEY
      api: openai-completions
      baseURL: ${gatewayURL}
      compat:
        supportsDeveloperRole: false
        maxTokensField: max_tokens
      models:
${modelYaml}
`;

if (existsSync(settingsPath) && !force) {
  console.log(`\n${settingsPath} already exists. Re-run with --force to overwrite.`);
} else {
  mkdirSync(dshHome, { recursive: true });
  writeFileSync(settingsPath, yaml);
  console.log(`\nWrote ${settingsPath} with models: ${models.join(", ")}`);
}
